language: go
go:
- 1.6
script: go build ./... && go build ./cmd/tjts && go test -v ./...
before_deploy: mkdir -p upload && mkdir -p pkg && cp tjts pkg/ && cd pkg && tar -zcvf ../upload/tjts-${TRAVIS_COMMIT}.tgz . && echo ${TRAVIS_COMMIT} > ../upload/latest
deploy:
  provider: s3
  access_key_id: AKIAIHZKDSWU6PBCT72Q
  bucket: s3.lstoll.net
  local_dir: upload
  upload_dir: artifacts/tjts
  acl: public_read
  skip_cleanup: true
  on:
    repo: lstoll/tjts
    branch: master
  secret_access_key:
    secure: "OLqk+d3x/ccFFK2UpfExthe3UdKhtOnp9yKl42KqXKGrbuWL5y6m1ni/4PiD4hl7kOLfyBVUBwjc4lX71VP3/9sRAdg2cm9iqihGtIjK398lu4po9JOzDnfYeDf5dSINSthe1TNpXNFeST7BeolF1qiUQD02Jqteg1eZz3BPd8SWySkT+z/iCfj78trqGwrsEMsUPEVkzdoPdMOVZv5UQZNjqT7r6bQ34tsy//iwX2Sz5Qd1t7iHjqw4EQCA+vj2QyCJm+KI9bW7X3ugye+rUtFxJvkm5Zvb877cEW3MvuK5oxgMNXRt1eZLdD7qtXe+ntlG1YsTOpsLRDRkxTAMWvYPaRgInJFnTwGSswZrnlFZ1WaZdou6zSyrJb2l05u+Xe6MvlJ06BzdW9+/RALF4GPDei8sG5a7XZg4zXq2vQUXKcrzNKyZTIQJikf2RwR+H4nndvqx8vAAXoVgAEzP1JgGJ0Cn8vZtEnpYxEANOvxQV/M5viiURDqwA7OnC4i9eQLeMYTNgDntF/qalul2H58widvjtON3uiJK4/h/ktdOH+iXhQ/TSgJTGBwGNXNUW/v8Rs+7F37IVASybT8THXkBfAPNgaUtj+Rqx+1j0qVpp8lMkxAcd8L6KhTBHPNbtujUlNCA7zQgtkxXRCaTzo8AfmTFb56W6xu3BYNKjYw="
